name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install  # Adjust if using yarn
      - name: Build for production
        run: npm run export # Adjust if using yarn build
      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-export
          path: out  # Adjust if you used a different export path

